package com.example.demo.model;

public enum BoatType {

    FLATS_BOAT,
    BAY_BOAT,
    CENTER_CONSOLE_BOAT,
    CATAMARAN,
    KAYAK,
    INFLATABLE_BOAT,
    BASS_BOAT,
    AIR_BOAT,
    PONTOON_BOAT,
    CUDDY_CABIN_BOAT,
    PILOTHOUSE_BOAT,
    FLYBRIDGE_SPORTFISHING_BOAT
}
